name: Laravel CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-dev --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set Up SQLite Database (temporary for testing)
      run: |
        mkdir -p database
        touch database/database.sqlite

    # - name: Run Tests
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_HOST: ${{ secrets.DB_HOST }}
    #     DB_PORT: ${{ secrets.DB_PORT }}
    #     DB_DATABASE: ${{ secrets.DB_DATABASE }}
    #     DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #   run: php artisan test

  deploy:
    name: Deploy to EC2
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Install Dependencies
      run: composer install --no-dev --no-progress --prefer-dist

    - name: Build Assets
      run: npm ci && npm run production

    - name: Sync Files to EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: "35.154.241.153"
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Printing SSH Key: $SSH_KEY"
        echo "Printing Host: $HOST"
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -az --delete --exclude="node_modules" --exclude=".git" \
        ./ $USER@$HOST:/var/www/laravel

    - name: Run Laravel Commands on EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        ssh -i "laravel.pem" ubuntu@ec2-35-154-241-153.ap-south-1.compute.amazonaws.com
          cd /var/www/laravel
          composer install --no-dev --no-progress --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        EOF
